### ISSUE TITLE
example_ios_bangbang.py怎么才能抓包测试？

### ISSUE THREAD

**Issue by irabbit666666** [sledgeh4w/chomper#115]
ceair 在越狱设备下打开就闪退了

**Comment by sledgeh4w** [comment]
你遇到是应该不是越狱检测，而是 frida 检测，ceair 会检测文件 `/usr/sbin/frida-server`，最简单粗暴的办法就是 frida-server 启动之后把这个文件删掉，APP 就能正常打开了。

**Comment by irabbit666666** [comment]
真的是，感谢老哥，真的厉害
