### ISSUE TITLE
NSDictionary的description对象读取问题

### ISSUE THREAD

**Issue by Me9ur1** [sledgeh4w/chomper#89]
这是在chomper读取description的代码
![chompercode](https://github.com/user-attachments/assets/6f203360-de57-4b6e-9d9d-b8a0ff682987)

返回结果如下
![chomper](https://github.com/user-attachments/assets/0489c9d2-4d8c-4534-a600-b210c60aaff5)

在unidbg内使用dict.getDescription()的结果
![unidbg](https://github.com/user-attachments/assets/5bdeb28c-ccdc-4b02-a9b5-aafc87a3c7a5)

其中signature字段在chomeper内被转译了吗

**Comment by sledgeh4w** [comment]
可以提供下可执行文件和完整调用代码吗，我怀疑问题出在签名过程中，而不是 NSDictionary 上。

**Comment by Me9ur1** [comment]
[apps.zip](https://github.com/user-attachments/files/16836971/apps.zip)
打了个包，执行文件路径在代码里有

**Comment by Me9ur1** [comment]
我用frida调试了一下原app，发现在调用签名时，hook sysctl函数的返回值并替换成1（0为调用成功，1为失败），出来的签名就是chomper返回的字样

**Comment by sledgeh4w** [comment]
通过添加了一些处理可以使它能正常出结果，一些是项目本身的一些能力缺失，一些是该程序本身存在一些环境检测逻辑。但这样计算出的结果现在不能保障是无风险的，因为我简单看了一下，它的逻辑是有多处环境检查的，可能会被带入结果中，是否合法，我现在无法验证。

目前 sysctl 支持不完善，导致返回非零值（失败），这里固定为零，让程序认为调用成功，后续会计划在项目中完善
```python
from chomper.os.ios.hooks import register_hook

@register_hook("_sysctl")
def hook_sysctl(uc, address, size, user_data):
    return 0
```

目前未支持 getppid 的系统调用，这里直接返回固定值，后续会加在项目中
```python
from chomper.os.ios.syscall import register_syscall_handler

@register_syscall_handler(0x27)
def handle_sys_getppid(emu):
    return 1
```

该函数会调用 socket 进行一个类似环境检查的操作，让其固定返回 0
```python
emu.add_interceptor(adjust_sig_sdk.base + 0x19BF4, hook_retval(0))
```

该函数会调用 open，读取 /dev/urandom 来生成一个随机数，暂未支持，hook 跳过
```python
def hook_read_dev_urandom(uc, address, size, user_data):
    emu = user_data["emu"]

    a1 = emu.get_arg(0)
    a2 = emu.get_arg(1)

    emu.write_bytes(a1, bytes([random.randint(0, 255) for _ in range(a2)]))

emu.add_interceptor(adjust_sig_sdk.base + 0x19518, hook_read_dev_urandom)
```

结果示例：
```
{
    "adj_signing_id" = 1000000;
    algorithm = adj4;
    "app_token" = kzsasld6z08w;
    "headers_id" = 5;
    "native_version" = "3.13.1";
    signature = A54467B6B934F3ED700C439C206D3164F7705C1AFC06C2228705B158CAE42E863490C8DFCB8C5E25A14C4146FE6400FC81258CE91928847A19856D5BC849858F1AA61D19ED3D82BD6401077823ED68389E218E9946B9EDA8B3E777F178787D7FBAC88F43F8D1BD60AE844E0E6864B4C6C4773C7077D0B084B8E05EEB6B88C377;
}
```

**Comment by Me9ur1** [comment]
强，其实签名有一部分过程就是sha256，正常会走自定义sha256，非正常就是走默认sha256，签名我校验过了，没通过，我自己再看看有没有什么地方漏掉了
