### ISSUE TITLE
ImportError: cannot import name 'UC_HOOK_CODE_TYPE' from 'unicorn.unicorn' 

### ISSUE THREAD

**Issue by ljy0jy** [sledgeh4w/chomper#97]
unicorn 2.1.1

在chomper的core.py中 报错 from unicorn.unicorn import UC_HOOK_CODE_TYPE

在unicorn2.1.1中， 没有UC_HOOK_CODE_TYPE。

unicorn.py:
import sys as _sys

from .unicorn_const import (
    UC_VERSION_MAJOR as __MAJOR,
    UC_VERSION_MINOR as __MINOR,
    UC_VERSION_PATCH as __PATCH
)

__version__ = "%u.%u.%u" % (__MAJOR, __MINOR, __PATCH)

if _sys.version_info.major == 2:
    from .unicorn_py2 import *
else:
    from .unicorn_py3 import *

**Comment by sledgeh4w** [comment]
你好，这个问题已经在 #91 修复了，只是还没有发布，可以先 clone 使用最新的仓库代码
